### ISSUE TITLE
Change initialization of Iterable in ReactIterableAPI.swift to fix error Extra arguments at positions #5, #6 in calll

### ISSUE THREAD

**Issue by kaushal9250** [Iterable/react-native-sdk#140] opened 2021-06-04 04:11 UTC
Please change the **Iterable initialization code** in `**ReactIterableAPI.swift**` because the function you are calling doesn't have a defined method in your sdk. And because of that we got error `**Extra arguments at positions #5, #6 in cal**`
To resolve this error 
 [Error](https://imgur.com/q8Bd9Dt) [screenshot](https://imgur.com/q8Bd9Dt)

    IterableAPI.initialize2(apiKey: apiKey, 
                                    launchOptions: launchOptions,
                                    config: iterableConfig, 
                                    apiEndPointOverride: apiEndPointOverride, 
                                     linksEndPointOverride: linksEndPointOverride) { result in
                                     resolver(result)}
        
  it doesn't have this param in methods
    **linksEndPointOverride: linksEndPointOverride) { result in
                resolver(result)**

To run your example or integration in my app, I did the following changes and it works perfectly.
 
           
            IterableAPI.initialize2(apiKey: apiKey, 
                                    launchOptions: launchOptions,
                                    config: iterableConfig, 
                                    apiEndPointOverride: apiEndPointOverride, 
                                    callback: {result in resolver(result)}
                                    );
        }

**Comment by roninopf** [comment] 2021-06-23 21:56
Hi @kaushal9250 ! Thanks for writing this in, and apologies for the delay in responding.

I believe this was caused by our packaging being out of sync with the tests; I'm not seeing this anymore, and I've also fixed another error the integration testing had in [this PR](https://github.com/Iterable/react-native-sdk/pull/145).

I'll be closing this ticket, but please feel free to submit a ticket or PR if you come across something else. Thanks!

**Closed by roninopf** 2021-06-23 21:56 UTC
